/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lots */
        get: operations["list_lots_api_lots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lots/{lot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lot Detail */
        get: operations["lot_detail_api_lots__lot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lots/{lot_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lot History
         * @description Default range: the 24 h ending at the lot's newest window (not wall-clock now).
         */
        get: operations["lot_history_api_lots__lot_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lots/{lot_id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Slot Snapshot */
        get: operations["slot_snapshot_api_lots__lot_id__slots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pipeline */
        get: operations["pipeline_api_pipeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertPage */
        AlertPage: {
            /** Items */
            items: components["schemas"]["AlertRow"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** AlertRow */
        AlertRow: {
            /** Alert Id */
            alert_id: string;
            /** Cleared At */
            cleared_at: string | null;
            /** Duration S */
            duration_s: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "FULL_LOT" | "SENSOR_OFFLINE";
            /** Lot Id */
            lot_id: string;
            /** Message */
            message: string;
            /** Occupancy Pct */
            occupancy_pct: number | null;
            /**
             * Raised At
             * Format: date-time
             */
            raised_at: string;
            /** Sensor Id */
            sensor_id: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "cleared";
        };
        /** BrokerInfo */
        BrokerInfo: {
            /** Host */
            host: string;
            /** Id */
            id: number;
            /** Leader Partitions */
            leader_partitions: number;
            /** Port */
            port: number;
        };
        /** ConsumerGroupInfo */
        ConsumerGroupInfo: {
            /** Group Id */
            group_id: string;
            /** Members */
            members: components["schemas"]["GroupMember"][];
            /** Partitions */
            partitions: components["schemas"]["GroupPartition"][];
            /** Rebalancing */
            rebalancing: boolean;
            /** State */
            state: string;
            /** Total Lag */
            total_lag: number;
        };
        /** GroupMember */
        GroupMember: {
            /** Client Id */
            client_id: string;
            /** Host */
            host: string;
            /** Partitions */
            partitions: string[];
        };
        /** GroupPartition */
        GroupPartition: {
            /** Committed */
            committed: number | null;
            /** End Offset */
            end_offset: number;
            /** Lag */
            lag: number;
            /** Member */
            member: string | null;
            /** Partition */
            partition: number;
            /** Topic */
            topic: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Database */
            database: boolean;
            /** Kafka Feed */
            kafka_feed: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Websocket Clients */
            websocket_clients: number;
        };
        /** History */
        History: {
            /** Lot Id */
            lot_id: string;
            /** Points */
            points: components["schemas"]["HistoryPoint"][];
            /**
             * Range End
             * Format: date-time
             */
            range_end: string;
            /**
             * Range Start
             * Format: date-time
             */
            range_start: string;
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "5m" | "1h";
        };
        /** HistoryPoint */
        HistoryPoint: {
            /** Avg Occupancy Pct */
            avg_occupancy_pct: number;
            /** Avg Occupied */
            avg_occupied: number;
            /** Closed */
            closed: boolean;
            /** Entries */
            entries: number;
            /** Exits */
            exits: number;
            /** Max Occupied */
            max_occupied: number;
            /** Min Occupied */
            min_occupied: number;
            /** Unique Vehicles Est */
            unique_vehicles_est: number | null;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /** LotDetail */
        LotDetail: {
            /** Capacity */
            capacity: number;
            /** Columns */
            columns: number;
            /** Dwell Minutes Est */
            dwell_minutes_est: number | null;
            /** Entries 24H */
            entries_24h: number;
            /** Exits 24H */
            exits_24h: number;
            /** Full Since */
            full_since: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Lot Id */
            lot_id: string;
            /** Name */
            name: string;
            /** Occupancy Pct */
            occupancy_pct: number | null;
            /** Occupied */
            occupied: number | null;
            /**
             * Personality
             * @enum {string}
             */
            personality: "office" | "mall" | "station";
            /** Slot Ids */
            slot_ids: string[];
            /** Unique Vehicles Est */
            unique_vehicles_est: number | null;
        };
        /** LotSummary */
        LotSummary: {
            /** As Of */
            as_of: string | null;
            /** Capacity */
            capacity: number;
            /** Lot Id */
            lot_id: string;
            /** Name */
            name: string;
            /** Occupancy Pct */
            occupancy_pct: number | null;
            /** Occupied */
            occupied: number | null;
            /**
             * Personality
             * @enum {string}
             */
            personality: "office" | "mall" | "station";
            /** Spark */
            spark: number[];
        };
        /** Overview */
        Overview: {
            /** Active Alerts */
            active_alerts: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Lots */
            lots: components["schemas"]["LotSummary"][];
            /** Occupancy Pct */
            occupancy_pct: number;
            /** Total Capacity */
            total_capacity: number;
            /** Total Occupied */
            total_occupied: number;
        };
        /** PartitionInfo */
        PartitionInfo: {
            /** End Offset */
            end_offset: number;
            /** Isr */
            isr: number[];
            /** Leader */
            leader: number;
            /** Partition */
            partition: number;
            /** Replicas */
            replicas: number[];
        };
        /** PipelineStats */
        PipelineStats: {
            /** Brokers */
            brokers: components["schemas"]["BrokerInfo"][];
            /** Dlq Messages */
            dlq_messages: number;
            /** Error */
            error: string | null;
            /** Events Per S */
            events_per_s: number | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Groups */
            groups: components["schemas"]["ConsumerGroupInfo"][];
            /** Late Messages */
            late_messages: number;
            /** Latency P50 S */
            latency_p50_s: number | null;
            /** Latency P95 S */
            latency_p95_s: number | null;
            /** Rebalances */
            rebalances: components["schemas"]["RebalanceEvent"][];
            /** Topics */
            topics: components["schemas"]["TopicInfo"][];
        };
        /** RebalanceEvent */
        RebalanceEvent: {
            /** Description */
            description: string;
            /** Group Id */
            group_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** SlotSnapshot */
        SlotSnapshot: {
            /** Lot Id */
            lot_id: string;
            /** Slots */
            slots: components["schemas"]["SlotState"][];
        };
        /** SlotState */
        SlotState: {
            /** Occupied */
            occupied: boolean | null;
            /** Slot Id */
            slot_id: string;
            /** Ts */
            ts: string | null;
        };
        /** TopicInfo */
        TopicInfo: {
            /** Name */
            name: string;
            /** Partitions */
            partitions: components["schemas"]["PartitionInfo"][];
            /** Total Messages */
            total_messages: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    alerts_api_alerts_get: {
        parameters: {
            query?: {
                kind?: ("FULL_LOT" | "SENSOR_OFFLINE") | null;
                status?: ("active" | "cleared") | null;
                lot_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_lots_api_lots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotSummary"][];
                };
            };
        };
    };
    lot_detail_api_lots__lot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lot_history_api_lots__lot_id__history_get: {
        parameters: {
            query?: {
                resolution?: "5m" | "1h";
                start?: string | null;
                end?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["History"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    slot_snapshot_api_lots__lot_id__slots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    pipeline_api_pipeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStats"];
                };
            };
        };
    };
}
